#####################
# register a new user
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "name": "karundangata",
    "email": "karundangata@gmail.com",
    "password": "Qwerty12!",
    "acceptTos": "yes"
}


######################
# login an existing user
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "karundangata@gmail.com",
    "password": "Qwerty12!" 
}


######################
# can knowingly change it in the app
# where the forgot password url should redirect you
# change user password
POST http://localhost:4000/auth/change-password/2f0e8d2-c66c-4cb8-ae18-b695d3d269b9
Content-Type: application/json

{
    "newPassword": "Pass123!",
    "confirmNewPassword": "Pass123!"
}

#######################
# on login
# forgot password
POST http://localhost:4000/auth/forgot-password
Content-Type: application/json

{
    "email": "ngataboni@gmail.com"
}


######################
# get all the users in the db
GET http://localhost:4000/auth/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxYmFhMDA0LWI1Y2YtNDVlOS05NzNlLTQzOTNiOGY3MGIzMyIsIm5hbWUiOiJibHVlIiwiZW1haWwiOiJuYWthbXVyYUBnbWFpbC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTcyMTMxODQ5OCwiZXhwIjoxNzIzMDQ2NDk4fQ.0tSHhg4BABqH0fzApRZB95BAzKoU0E6N1L3ZiVvWOzo



######################
# get a specific user by id
GET http://localhost:4000/auth/b6118ff0-993b-44c5-98d3-cf789aef2d6d
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxYmFhMDA0LWI1Y2YtNDVlOS05NzNlLTQzOTNiOGY3MGIzMyIsIm5hbWUiOiJibHVlIiwiZW1haWwiOiJuYWthbXVyYUBnbWFpbC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTcyMTMxODQ5OCwiZXhwIjoxNzIzMDQ2NDk4fQ.0tSHhg4BABqH0fzApRZB95BAzKoU0E6N1L3ZiVvWOzo



######################
# get a specific user by email
GET http://localhost:4000/auth/user-email
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxYmFhMDA0LWI1Y2YtNDVlOS05NzNlLTQzOTNiOGY3MGIzMyIsIm5hbWUiOiJibHVlIiwiZW1haWwiOiJuYWthbXVyYUBnbWFpbC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTcyMTMxODQ5OCwiZXhwIjoxNzIzMDQ2NDk4fQ.0tSHhg4BABqH0fzApRZB95BAzKoU0E6N1L3ZiVvWOzo

{
    "email": "rafii@gmail.com"
}


######################
# update a users credentials. with id
PATCH http://localhost:4000/auth/20996421-aab2-4c6f-ad01-10e8186f8081
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxYmFhMDA0LWI1Y2YtNDVlOS05NzNlLTQzOTNiOGY3MGIzMyIsIm5hbWUiOiJibHVlIiwiZW1haWwiOiJuYWthbXVyYUBnbWFpbC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTcyMTMxODQ5OCwiZXhwIjoxNzIzMDQ2NDk4fQ.0tSHhg4BABqH0fzApRZB95BAzKoU0E6N1L3ZiVvWOzo


{
    "name": "Mrs. Anyona",
    "email": "Anyona@gmail.com",
    "password": "Pass123!"
}


######################
DELETE http://localhost:4000/auth/057392d7-7533-4faa-8eb7-d6d88a2df523
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxYmFhMDA0LWI1Y2YtNDVlOS05NzNlLTQzOTNiOGY3MGIzMyIsIm5hbWUiOiJibHVlIiwiZW1haWwiOiJuYWthbXVyYUBnbWFpbC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTcyMTMxODQ5OCwiZXhwIjoxNzIzMDQ2NDk4fQ.0tSHhg4BABqH0fzApRZB95BAzKoU0E6N1L3ZiVvWOzo



######################

